### PR TITLE
fix: fixed spacing issues on mobile and large view and fixed text siz…

### LINKED ISSUE #174: FEATURE: Adjust the way abb. are displayed on mobile.
### Description

On mobile devices, around the search button, when a slang is entered the abbreviation falls way below the submit button. Perhaps we could redesign it in such a way that we move the results up to align side by side with the submit button on mobile devices.

See screenshot to see the problem.

### Screenshots

abbreve-git-fork-ctoffanin-add-spinner-njong392 vercel app_(iPhone SE)

### LINKED ISSUE #188: Abbreve forms
What issue are you facing? Missing Abbreviation
Which slang/feature/bug? :Uwc
Bug description:

### LINKED ISSUE #206: BUG: little or no padding added && large text on mobile view
### Description

There is no padding before those tweets 
And in between the tweets the padding top is much

### Screenshots

Screenshot_20230110-004925

### PR DESCRIPTION
**Pull request by dev-phantom**
…e issues

fixes #174 
fixes #206 
Closes #

### What new changes did you make? Tick all applicable boxes
- [ ] Added new abbreviation
- [ ] Fixed something in the source code
- [x] Added a new feature
- [ ] Fixed the docs (README.md, CONTRIBTUING.md, etc)

### Describe the new changes you added.
i reduced and added some padding && margin to the appriopriate place

### Share a screenshot of new changes
image

> > Sorry, but I had to ask. How does this PR close #188 ?
> 
> sorry about this that issue was wrongly tagged

i have corrected this

### CODE REVIEW

File: src/components/form.jsx [hunk 1]
```diff
@@ -122,16 +122,16 @@ const Form = () => {
           {isLoading && <LoadingSpinner />}
 
           {data && (
-            <>
-              <div className="mt-2 text-purple font-bold text-xl ml-2 dark:text-deeppurple">
+            <div className="bg-ash shadow-lg border-2 border-deeppurple py-2 pl-2 rounded-lg mt-4">
+              <div className="mt-1 text-purple font-bold text-xl ml-2 dark:text-deeppurple">
```
Comment (Njong392) [inline src/components/form.jsx:126]: In light mode the definition is in `text-deeppurple`, but in dark mode it's back to `text-purple`. Since in dark mode the abbrevaition region is surrounded by  `bg-ash`, the text should remain `text-deepurple`. What do u think?
```suggestion
              <div className="mt-1 font-bold text-xl ml-2 text-deeppurple">
```

**Review by Njong392 — CHANGES_REQUESTED** [review]

**Comment by Njong392** [comment]
Sorry, but I had to ask. How does this PR close #188 ?

File: src/components/form.jsx (hunk 1 above)
Comment (dev-phantom) [reply src/components/form.jsx:126]: opps sorry about that i will fix that and re-push

**Comment by dev-phantom** [comment]
> Sorry, but I had to ask. How does this PR close #188 ?

sorry about this that issue was wrongly tagged

File: src/components/form.jsx (hunk 1 above)
Comment (dev-phantom) [reply src/components/form.jsx]: i've corrected  this

**Review by Njong392 — APPROVED** [review]
Looks great! Thank you for this :tada:
