### PR TITLE
Fixed issue on medium screens

### LINKED ISSUE #208: BUG: the medium screen view is not responsive
### There is an issue with responsiveness on the medium screen 
i could fix this also if am assigned to it

### Screenshots

image

### PR DESCRIPTION
**Pull request by dev-phantom**
Closes #208 

### What new changes did you make? Tick all applicable boxes
- [ ] Added new abbreviation
- [ ] Fixed something in the source code
- [x] Added a new feature
- [ ] Fixed the docs (README.md, CONTRIBTUING.md, etc)

### Describe the new changes you added.
I added responsiveness to the medium screen
added some hover to the tweet card 

### Share a screenshot of new change
localhost_5173_(iPad Air) (1)

### CODE REVIEW

File: src/components/hero.jsx [hunk 1]
```diff
@@ -49,8 +49,8 @@ const Hero = () => {
 
       <Form />
 
-      <section className="block justify-center  items-center md:flex">
-        <div className="md:w-1/2 md:pr-20 md:text-left text-center">
+      <section className="block justify-center  items-center md:flex md:flex-col-reverse xl:flex xl:flex-row lg:flex lg:flex-row">
+        <div className="lg:w-1/2 px-10 pt-5 lg:px-0 lg:pr-20 md:text-left text-center">
           <p className="text-purple font-bold text-2xl lg:text-3xl dark:text-deeppurple">
```
Comment (Njong392) [inline src/components/hero.jsx:54]: I think adding a `lg:text-center` here would make this text look a bit more uniform in terms of alignment with the one below. What do you think?

File: src/components/hero.jsx [hunk 2]
```diff
@@ -49,8 +49,8 @@ const Hero = () => {
 
       <Form />
 
-      <section className="block justify-center  items-center md:flex">
-        <div className="md:w-1/2 md:pr-20 md:text-left text-center">
+      <section className="block justify-center  items-center md:flex md:flex-col-reverse xl:flex xl:flex-row lg:flex lg:flex-row">
```
Comment (Njong392) [inline src/components/hero.jsx:52]: Apologies for not having caught this before, `lg` applies classes to all large screens and above. So it will include `xl`. Adding `lg` and `xl` is a  bit redundant I think.
 ```suggestion
      <section className="block justify-center  items-center md:flex md:flex-col-reverse  lg:flex lg:flex-row">
```

File: src/components/hero.jsx [hunk 3]
```diff
@@ -101,8 +101,8 @@ const Hero = () => {
         </div>
       </section>
 
-      <section className=" justify-center gap-10 mt-10 items-center flex flex-col lg:flex-row">
-        <div className="border-2 p-4 rounded-lg border-purple md:rotate-3 relative md:mt-0 dark:border-deeppurple">
+      <section className=" justify-center lg:gap-10 mt-10 items-center flex flex-col lg:flex-row">
+        <div className="border-2 p-4 rounded-lg border-purple lg:rotate-3 hover:lg:rotate-0 hover:lg:ease-in-out hover:lg:duration-300 relative md:mt-0 dark:border-deeppurple">
```
Comment (Njong392) [inline src/components/hero.jsx:105]: Looked at this animation for a bit again. On enter, it eases in just fine with a nice duration. But on exit of hover, it immediately just springs back to its normal position, and that does not feel right.

**Review by Njong392 — CHANGES_REQUESTED** [review]

**Comment by Njong392** [comment]
Also, I noticed that you had made changes to the `package.json` file. This may cause breaking in the future. Could you please revert it? Did you also make slight additions  to the `public/server/db` ? That is what your PR shows.

**Comment by dev-phantom** [comment]
> Also, I noticed that you had made changes to the `package.json` file. This may cause breaking in the future. Could you please revert it? Did you also make slight additions  to the `public/server/db` ? That is what your PR shows.

I actually didn't make any changes there 
And I've also reverted the file still don't know why this keeps popping up 🤔

File: src/components/form.jsx [hunk 4]
```diff
@@ -69,22 +69,24 @@ const Form = () => {
...
+      <section className="block justify-center md:pb-16 md:flex md:flex-col lg:flex xl:flex lg:flex-row xl:flex-row items-center">
+        <div className="md:w-full lg:pr-20 lg:w-1/2 flex flex-col">
+          <h2 className="lg:text-left text-center text-purple font-bold text-xl md:text-2xl lg:text-3xl  dark:text-deeppurple">
             <span className="text-ash dark:text-dark">
               Start by entering a slang,
             </span>{" "}
             and our dictionary will spit out an abbreviation.{" "}
           </h2>
-          <p className="text-gray text-left lg:text-center text-sm mt-5">
+          <p className="text-gray text-leftlg:text-left md:text-center px-0 md:px-10 xmd:px-20 lg:px-0 xl:px-0 text-sm mt-5">
```
Comment (Njong392) [inline src/components/form.jsx:80]: I apologise for constantly reviewing, but you joined two classes here that I think should have a space in between.
```suggestion
          <p className="text-gray text-left lg:text-left md:text-center px-0 md:px-10 xmd:px-20 lg:px-0 xl:px-0 text-sm mt-5">
```

**Review by Njong392 — CHANGES_REQUESTED** [review]

**Comment by Njong392** [comment]
> I actually didn't make any changes there And I've also reverted the file still don't know why this keeps popping up 🤔

I think it has something to do with linters? Maybe you have some linter that formatted the files?

File: src/components/hero.jsx (hunk 1 above)
Comment (dev-phantom) [reply src/components/hero.jsx:54]: image

this right?

**Comment by dev-phantom** [comment]
hoping this fix it 

@Njong392 let me know if you encounter any other error
