### PR TITLE
fix search bar visibility

### LINKED ISSUE #298: BUG: <Search bar visibility>
### Description

search input field visibility is not clear in light mode 
increasing search input shadow opacity will help.

tested on mac using chrome browser.

### Screenshots

image

### PR DESCRIPTION
**Pull request by milekboy**
Closes #298

### What new changes did you make? Tick all applicable boxes
- [ ] Added new abbreviation
- [ - ] Fixed something in the source code
- [ ] Added a new feature
- [ ] Fixed the docs (README.md, CONTRIBTUING.md, etc)

### Describe the new changes you added.
I made the search input bar more visible in light mode, by adding a border

### CODE REVIEW

File: src/components/form.jsx [hunk 1]
```diff
@@ -87,7 +87,7 @@ const Form = () => {
           <form
             className="block md:flex items-center justify-start gap-2"
             id="form">
-            <div className="bg-ash h-11 rounded-full flex items-center p-3 mt-4 md:mt-0 dark:shadow-lg">
+            <div className="bg-ash h-11 rounded-full flex items-center p-3 mt-4 md:mt-0 dark:shadow-lg border-solid border-2 border-deeppurple">
```
Comment (Njong392) [inline src/components/form.jsx:90]: Sweet! This looks really cool. Thank you very much for the new adjustments.

**Review by Njong392 — APPROVED** [review]

**Comment by milekboy** [comment]
thanks😊
